services:
  frontend:
    container_name: systemsmatic-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend_build:/app/out
    expose:
      - "3000"

  backend:
    container_name: systemsmatic-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: ./backend/.env.production
    expose:
      - "3001"
    depends_on:
      - redis

  redis:
    container_name: systemsmatic-redis
    image: redis:7
    expose:
      - "6379"

  node-exporter:
    container_name: systemsmatic-node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"

  cadvisor:
    container_name: systemsmatic-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    container_name: systemsmatic-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: systemsmatic-grafana
    image: grafana/grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  nginx:
    container_name: systemsmatic-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/var/www/frontend
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
      - grafana

volumes:
  frontend_build:
  grafana_data:
