global:
  scrape_interval: 5s

scrape_configs:
  # --- Backend NestJS ---
  - job_name: "nest-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:3001"]

  # --- Node Exporter (metrics machine) ---
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # --- cAdvisor (stats Docker containers) ---
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # --- Prometheus lui-mÃªme ---
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
